
package cl.experti.admission.ws.login;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-05T11:48:04.481-04:00
 * Generated source version: 3.0.4
 * 
 */
public final class LoginService_LoginServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://login.ws.admission.experti.cl", "LoginServiceService");

    private LoginService_LoginServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LoginServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LoginServiceService ss = new LoginServiceService(wsdlURL, SERVICE_NAME);
        LoginService port = ss.getLoginServicePort();  
        
        {
        System.out.println("Invoking userLogin...");
        cl.experti.admission.ws.login.UserLogin _userLogin_parameters = null;
        cl.experti.admission.ws.login.UserLoginResponse _userLogin__return = port.userLogin(_userLogin_parameters);
        System.out.println("userLogin.result=" + _userLogin__return);


        }

        System.exit(0);
    }

}
