package cl.experti.admission.ws.login;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-08T17:23:18.080-03:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://login.ws.admission.experti.cl", name = "LoginService")
@XmlSeeAlso({ObjectFactory.class, cl.experti.admission.ws.login.dto.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LoginService {

    @WebMethod
    @WebResult(name = "userLoginResponse", targetNamespace = "http://login.ws.admission.experti.cl", partName = "parameters")
    public UserLoginResponse userLogin(
        @WebParam(partName = "parameters", name = "userLogin", targetNamespace = "http://login.ws.admission.experti.cl")
        UserLogin parameters
    );
}
