package cl.experti.admission.ws.login;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-08T17:23:18.087-03:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "LoginServiceService", 
                  wsdlLocation = "file:/home/cavallinux/dev/src/orange/test-admission/admission-test-ws-stubs/admission-test-wsclients/admission-test-login-wsclient/src/main/wsdl/LoginService.wsdl",
                  targetNamespace = "http://login.ws.admission.experti.cl") 
public class LoginServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://login.ws.admission.experti.cl", "LoginServiceService");
    public final static QName LoginServicePort = new QName("http://login.ws.admission.experti.cl", "LoginServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/cavallinux/dev/src/orange/test-admission/admission-test-ws-stubs/admission-test-wsclients/admission-test-login-wsclient/src/main/wsdl/LoginService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LoginServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/cavallinux/dev/src/orange/test-admission/admission-test-ws-stubs/admission-test-wsclients/admission-test-login-wsclient/src/main/wsdl/LoginService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LoginServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LoginServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LoginServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LoginServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LoginServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns LoginService
     */
    @WebEndpoint(name = "LoginServicePort")
    public LoginService getLoginServicePort() {
        return super.getPort(LoginServicePort, LoginService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginService
     */
    @WebEndpoint(name = "LoginServicePort")
    public LoginService getLoginServicePort(WebServiceFeature... features) {
        return super.getPort(LoginServicePort, LoginService.class, features);
    }

}
